name: ğŸ… Plugin Assessor

on:
  schedule:
    - cron: "30 03 01 */3 *"
  workflow_dispatch:

env:
  TERM: xterm-256color

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: ğŸ“¦ Dependencies
        run: sudo apt-get update && sudo apt-get install zsh -yq
      - name: ğŸš€ Run Assessor
        run: |
          cd docs/zsh-plugins-top100
          ./render.zsh
      - name: â˜‘ï¸ Commit files
        run: |
          cp -vf docs/zsh-plugins-top100/README.md docs/wiki/zi/06-knowledge-base/Zsh-Plugins-top100.md
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a
      - name: ğŸ“¤ Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
