name: ✅ Check Markdown links

on: 
  push:
  pull_request_target:
  
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: ⤵️ Check out code from GitHub
      uses: actions/checkout@master
    - name: ✨ Checking Markdown links
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        check-modified-files-only: 'yes'
        folder-path: 'wiki, docs'
        config-file: '.github/links-config.yml'
        #file-path: 'REAMDE.md, ./LICENSE'
#
#  <!-- markdown-link-check-disable -->
# # Section
#
# #Disbale link checking in this section. Ignore this [Bad Link](https://exampleexample.cox)
# <!-- markdown-link-check-enable -->
