---
name: ğŸ“– Zsh

on:
  push:
    paths:
      - "wiki/zsh/**"
  pull_request:
    paths:
      - "wiki/zsh/**"
  workflow_dispatch:

jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - name: âš¡ Install zsdoc
        run: |
          sudo apt-get install -y zsh tree
          sudo make -C lib/zsdoc install
      - name: ğŸ’ Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: ğŸ“ Install asciidoctor-pdf and rouge
        run: |
          gem install asciidoctor-pdf rouge
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: â™»ï¸ Generate Documentation
        run: |
          make -C wiki/zsh clean
          make -C wiki/zsh all
      - name: â™»ï¸ Compress the Zsh Documentation
        run: tar cvzf zsh-wiki.tar.gz wiki/zsh
      - name: Upload zsh-wiki.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: â™»ï¸ Zsh Documentation
          path: zsh-wiki.tar.gz
      - name:  ğŸš€ Deploy to GitHub Pages
        run: |
          make -C wiki/zsh prep-gh-pages
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add wiki/zsh/gh-pages
          git commit -m "Zsh Documentation Update" -a
          git subtree push --prefix wiki/zsh/gh-pages origin gh-pages

#      - name: ğŸš€ Deploy to GitHub Pages
#        uses: Cecilapp/GitHub-Pages-deploy@v3
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          email: ${{ secrets.GH_MAIL }}
#          build_dir: wiki/zsh/gh-pages
