---
name: ğŸ“– ZI

on:
  push:
    paths:
      - "wiki/zi/**"
  workflow_dispatch:

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v2
      - name: ğŸ— Prepare wiki
        run: make -C wiki/zsh to-wiki-pages
      - name: ğŸ“¤ Sync Docs to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v2
        env:
          WIKI_DIR: wiki/zi/
          REPO: z-shell/zi
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GH_MAIL: ${{ secrets.GH_MAIL }}
          GH_NAME: ${{ github.repository_owner }}
          #EXCLUDED_FILES: "wiki/zi/drafts/"
